### ISSUE TITLE
Apple Pay activation

### ISSUE THREAD

**Issue by giorgio80** [Seeed-Studio/PN532#100]
Dear, 
need to read raid card only for my application. 

When attaching an iPhone near the reader Apple Pay automatically activate. 

Is there's such a way to configure the board to read raid card only and not scanning for NFC?

**Comment by lesterlo** [comment]
This is the feature of Apple iPhone. When the iPhone detects any NFC/ RF wave, Apple Pay feature will activate automatically.

I think there is no way to disable this feature.

**Comment by nutsmuggler** [comment]
The only way to prevent this is to use the PN532 in card emulation mode.
This way the iPhone will see it as a card, and read it correctly.

**Comment by Cincinnatu** [comment]
> 亲爱的，只需要为我的应用程序读取 raid card。
> 
> 将 iPhone 连接到读卡器附近时，Apple Pay 会自动启动。
> 
> 有没有办法将板子配置为仅读取 RAID 卡而不扫描 NFC？
Hello Is the issue resolved now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
