### ISSUE TITLE
Chip reference PN532

### ISSUE THREAD

**Issue by OnJuanTrack** [Seeed-Studio/PN532#102]
At this moment I'm working with the NFC module PN532, I have 2 modules of this pn532. They are apparently equal, but they don't work equals. With the module #1 I can read the UID of differents Tags (Credit card, bus pay card, bank card and Mifare classic), with the module #2 I can read the UID only in the Mifare Classic card.

One important thing about this modules is that with the module #1 I can read the UID at 5 cm, with the module #2 I can read the UID at 2.5 cm, so I think that maybe the module #1 have more antenna Gain and can read the other tags.

Also I've saw the reference in the main chip in each module and they are different.

Module #1 chip reference: 5321 06 CXX963 02 TS09501
Module #2 chip reference: 5321 06 CWW607 08 TSD9181

Both modules have the same distribution and pcb, all the tracks are equal and the position of the components is equal.

I think that there are 2 possibilities:

the first one -> some capacitors or inductors have a different value and the antenna gain is higher, then the module #1 can read the more secure cards (Credit card, buy pay car, bank card).

the second one -> the chip reference is very important and the reference 5321 06 CWW607 08 TSD9181 can't read this kind of tags.

Thanks

**Comment by Cincinnatu** [comment]
Hello, the actual read distance typically depends not only on the parameters of the NFC module but also on the size and parameters of the coil being read.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
