### ISSUE TITLE
PN532 + Ethernet

### ISSUE THREAD

**Issue by OnJuanTrack** [Seeed-Studio/PN532#103]
Hi! At this moment I'm working on a project that needs a NFC module with Ethernet communication, I'm using the ESP8266 as a central microcontroller.

I've selected the PN532 as a NFC module because with this module I can read the UID of credit card, bus pay card, passport and more ... As my microcontroller is the ESP8266 I only can use the SPI communication with the PN532 because the I2C is not supported.

The Ethernet module that I'm using is ENC28j60, with this module I can query web services and it works ok.

Each module works okay with my microcontroller, but the problem is when I try to use both modules in the same code.

If I initialize first the Ethernet (ENC28j60) module and after the NFC module (PN532) then in the loop I can read NFC tags but I can't send petitions to the web service.

When I initialize first the NFC module (PN532) and after the Ethernet module (ENC28j60) I can sent petitions to the web service but I can't read NFC tags.

I think that maybe the PN532 modify the SPI communication o something like this and this is the reason why I can use the ethernet after initilize the PN532.

Thanks.

**Comment by Cincinnatu** [comment]
Is this issue currently resolved? If not, you need to provide more information.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
