### ISSUE TITLE
Not a issue but question?

### ISSUE THREAD

**Issue by akshar001** [Seeed-Studio/PN532#104]
For one of my application i will need both to emulate tag and use p2p ndef. at a time.
Can i do that? With current library or is is it even possible with using a chip?

**Comment by Johannf78** [comment]
I am struggling with the same problem. Seems like technically it is possible. But have not been able to get it working. I think the phone / chips where more intended to read NFC cards, than to emulate a card. I am think now of using NFC to initiate the connection then go over to BLE.

**Comment by DavidDHansson** [comment]
I am also in the same situation. I am looking into using threads. Thinking if a write has occurred within a sec or something, the loop can continue running, and then after it will continue checking write.

**Comment by Cincinnatu** [comment]
Hello Is this issue currently resolved?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
