### ISSUE TITLE
I could really use some help, Arduino to Android com.

### ISSUE THREAD

**Issue by Brayden1000** [Seeed-Studio/PN532#105]
Hi! I am trying to write a simple text message to my note 10 android phone. I can't seem to get it to read the phone on the p2p example so I tried to emulate it (a PN532 breakout board) to a tag and I get a "Couldn't read NFC tag" prompt on my phone, and I think it because it's sending a UID I don't know. So I was wondering if I could specifically change the "emulate_tag" example to write a text message, not a UID. Also if anyone knows why my device would give me that error or has code that should beam a simple text message to an android device that would be much appreciated I have been picking away at this for about a week now and I just want it to work so bad. Any help is much appreciated please let me know if you need any more info!

Thank you!!!

**Comment by Cincinnatu** [comment]
Is this issue currently resolved? If not, you need to provide more information.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
