### ISSUE TITLE
Check for Card runs very slow.

### ISSUE THREAD

**Issue by Sanevent** [Seeed-Studio/PN532#108]
I'm currently having problems with this library because I'm trying to code something which has to run very fast ( < 100ms update time). The problem is, that the library blocks the code for at least 1 second while checking for a card, which is way too slow. Did I missed some configuration or is there a workaround for this problem?

**Comment by Cincinnatu** [comment]
Is this issue currently resolved? If not, you need to provide more information.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
