### ISSUE TITLE
P2P SPI pn532 with two arduino's

### ISSUE THREAD

**Issue by joinmod** [Seeed-Studio/PN532#110]
Hi, i cant to get pn532 to work with second one. For some reason they dont see each other but on transive part i can send messages to android but because of removing beam on latest ver. android, arduino fails it.
The same reason i cant check recive part (i dont have anything to send message) but i am pretty sure he is working because i can read passive RFID tag on other sketch.

so... how i make to work them?

**Comment by Cincinnatu** [comment]
Hello, has this issue been resolved? If not, please provide more information.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
