### ISSUE TITLE
SPI Wiring Not working on d1 mini

### ISSUE THREAD

**Issue by 6000850** [Seeed-Studio/PN532#113]
Hello
This wiring is SPI, but after uploading the ReadTag.ino code, the message "Didn't find PN53x board" is displayed.

My Board : 
`Wemos D1 Mini`

My Wiring :
```
SCK => D5
MISO => D6
MOSI => D7
SS => D3
VCC => 3.3V
GND => GND
```
**When I connect the SS pin to D8. Upload gives an error and the code is not uploaded**

ReadTag.ino

```
#include <NfcAdapter.h>
#include <PN532/PN532/PN532.h>

    #include <SPI.h>
    #include <PN532/PN532_SPI/PN532_SPI.h>
    PN532_SPI pn532spi(SPI, 0);
    NfcAdapter nfc = NfcAdapter(pn532spi);

void setup(void) {
    SERIAL.begin(9600);
    SERIAL.println("NDEF Reader");
    nfc.begin();
}

void loop(void) {
    SERIAL.println("\nScan a NFC tag\n");
    if (nfc.tagPresent()) {
        NfcTag tag = nfc.read();
        tag.print();
    }
    delay(5000);
}
```

**Comment by 6000850** [comment]
Hello
No answer to this question?

**Comment by 6000850** [comment]
SoftwareSerial worked! but SPI NOT Working!! why!?

**Comment by Cincinnatu** [comment]
Hello, has this issue been resolved? If not, please provide more information.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
