### ISSUE TITLE
Poll 2 standard type of NFC card at the same time

### ISSUE THREAD

**Issue by lesterlo** [Seeed-Studio/PN532#114]
Could this library poll felica card and the ISO 14443A card at the same time?

I want to develop a card reader that accept felica standard and ISO 14443A standard.

For example `nfc.felica_Polling()` function polls felica nfc card type. And `nfc.readPassiveTargetID(PN532_MIFARE_ISO14443A)` polls ISO14443A nfc standard only.  Is there are any methods that can poll felica and iso14443A card in the same function?

**Comment by Cincinnatu** [comment]
Hello, has this issue been resolved? If not, please provide more information.

**Comment by lesterlo** [comment]
I don't think it is been resolved.

**Comment by Cincinnatu** [comment]
FeliCa and ISO 14443A belong to different NFC protocols and require different commands for polling. Switching between the two protocols requires reconfiguring the working mode, which makes it difficult to implement true polling of both types of cards.
