### ISSUE TITLE
_serial->write(0) pulls an error on some platforms

### ISSUE THREAD

**Issue by Ariel-International** [Seeed-Studio/PN532#116]
I solved this problem by adding (byte) as in:
`void PN532_HSU::wakeup()
{
    _serial->write((byte)0x55);
    _serial->write((byte)0x55);
    _serial->write((byte)0);
    _serial->write((byte)0);
    _serial->write((byte)0);
`
This works fine on SAMD.

**Comment by Cincinnatu** [comment]
Hello, has this issue been resolved? If not, please provide more information.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
