### ISSUE TITLE
Some functions don't manage readResponse correctly (SAMConfig return always false)

### ISSUE THREAD

**Issue by mywalkb** [Seeed-Studio/PN532#127]
I see some functions don't manage correctly the length 0 from readResponse.
For example SAMConfig return 0 length that it's correct from datasheet, but for this library return false.
I will not make a PR because because none manage it, if someone is interested I patched [here](https://github.com/mywalkb/PN532/commit/7b43cd4105d78d87ebb2c54d0998586f1fea4e72), in this patch there are also some improvements.

**Comment by Cincinnatu** [comment]
Hello！Can you describe the changes that you have made?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
