### ISSUE TITLE
error: call of overloaded 'requestFrom(int, unsigned int)' is ambiguous

### ISSUE THREAD

**Issue by freshrebel** [Seeed-Studio/PN532#131]
Hi

We loaded your library in the arduino libraries, started up the example ISO14443A_uid, but we get the following error:
Compiling library "PN532_I2C"
"C:\\Users\\Arno\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega4809 -DF_CPU=16000000L -DARDUINO=10820 -DARDUINO_AVR_NANO_EVERY -DARDUINO_ARCH_MEGAAVR -DMILLIS_USE_TIMERB3 -DNO_EXTERNAL_I2C_PULLUP "-IC:\\Users\\Arno\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\megaavr\\1.8.7\\cores\\arduino/api/deprecated" "-IC:\\Users\\Arno\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\megaavr\\1.8.7\\cores\\arduino" "-IC:\\Users\\Arno\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\megaavr\\1.8.7\\variants\\nona4809" "-IC:\\Users\\Arno\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\megaavr\\1.8.7\\libraries\\Wire\\src" "-IC:\\Users\\Arno\\Documents\\Arduino\\libraries\\PN532_I2C" "-IC:\\Users\\Arno\\Documents\\Arduino\\libraries\\PN532" "-IC:\\Users\\Arno\\Documents\\Arduino\\libraries\\NDEF" "C:\\Users\\Arno\\Documents\\Arduino\\libraries\\PN532_I2C\\PN532_I2C.cpp" -o "C:\\Users\\Arno\\AppData\\Local\\Temp\\arduino_build_657732\\libraries\\PN532_I2C\\PN532_I2C.cpp.o"
C:\Users\Arno\Documents\Arduino\libraries\PN532_I2C\PN532_I2C.cpp: In member function 'int8_t PN532_I2C::readAckFrame()':
C:\Users\Arno\Documents\Arduino\libraries\PN532_I2C\PN532_I2C.cpp:196:73: error: call of overloaded 'requestFrom(int, unsigned int)' is ambiguous
         if (_wire->requestFrom(PN532_I2C_ADDRESS,  sizeof(PN532_ACK) + 1)) {
                                                                         ^
In file included from C:\Users\Arno\Documents\Arduino\libraries\PN532_I2C\PN532_I2C.h:8:0,
                 from C:\Users\Arno\Documents\Arduino\libraries\PN532_I2C\PN532_I2C.cpp:5:
C:\Users\Arno\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.7\libraries\Wire\src/Wire.h:61:12: note: candidate: virtual size_t TwoWire::requestFrom(uint8_t, size_t)
     size_t requestFrom(uint8_t, size_t);
            ^~~~~~~~~~~
C:\Users\Arno\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.7\libraries\Wire\src/Wire.h:63:12: note: candidate: size_t TwoWire::requestFrom(int, int)
     size_t requestFrom(int, int);
            ^~~~~~~~~~~
Bibliotheek Wire op versie 1.0 in map: C:\Users\Arno\AppData\Local\Arduino15\packages\arduino\hardware\megaavr\1.8.7\libraries\Wire  wordt gebruikt
Bibliotheek PN532_I2C in map: C:\Users\Arno\Documents\Arduino\libraries\PN532_I2C (legacy) wordt gebruikt
Bibliotheek PN532 in map: C:\Users\Arno\Documents\Arduino\libraries\PN532 (legacy) wordt gebruikt
Bibliotheek NDEF in map: C:\Users\Arno\Documents\Arduino\libraries\NDEF (legacy) wordt gebruikt
exit status 1
Fout bij het compileren voor board Arduino Nano Every

![image](https://user-images.githubusercontent.com/10060982/182243703-2c7cd240-0694-4d3b-a9f7-295a3cc902f2.png)

can somebody help us?

Kind regards
Arno Deckx

**Comment by Cincinnatu** [comment]
Hello, has this issue been resolved? If not, please provide more information.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
