### ISSUE TITLE
PN532 Tag compatibility

### ISSUE THREAD

**Issue by marcodc-sys** [Seeed-Studio/PN532#132]
Hi, 
I am new to NFC technology, so sorry for this newbie question. I would like to know if PN532 chip to read/write  ST25TA02KB-D (NFC Forum TYPE A 2kB EEPROM) communicating with ISO 14443/A protocol. Thanks

**Comment by Cincinnatu** [comment]
Yes, the PN532 fully supports the ISO 14443-A protocol and is capable of reading and writing data to the ST25TA02KB-D tag. This means that users can communicate successfully with the tag using the PN532.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
