### ISSUE TITLE
Redefining NULL creates conflicts with other libraries

### ISSUE THREAD

**Issue by SergioArrighi** [Seeed-Studio/PN532#135]
Hello,

thanks for the great library.
I'm experiencing a conflict between this library and HttpClient as NULL is here redefined.
What is the reason why as standard definition was overridden and how can I accomodate to use both libraries at the same time?
Thanks and best regards

**Comment by Cincinnatu** [comment]
Hello, has this issue been resolved? If not, please provide more information.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
