### ISSUE TITLE
Issue with HAL during Tag Emulation Using Adafruit PN532 and SPI Interface

### ISSUE THREAD

**Issue by michelbarnich** [Seeed-Studio/PN532#143]
Hello,

I'm encountering an issue while attempting to emulate a tag using the Adafruit PN532 with the example provided in this repository. Specifically, I'm experiencing unexplained rejections of some commands by my Adafruit PN532. The PN532 HAL (referenced [here](https://github.com/Seeed-Studio/PN532/blob/40fa7418636da5e03b0126e38c221b143b24b5a4/PN532/PN532.cpp#L954)) is returning an error code (-2), leading to subsequent command failures.

I am utilizing the library with the SPI interface, and have followed the example code closely, with the only modification being the use of SPI instead of HSU. Could I be overlooking any critical setup or configuration steps required for successful SPI interface operation? Any guidance or suggestions would be greatly appreciated.

The log looks like this (after enabling debug):
```
tgInitAsTarget failed or timed out!write:  8C 5 4 0 12 34 56 20 1 FE A2 A3 A4 A5 A6 A7 C0 C1 C2 C3 C4 C5 C6 C7 FF FF AA 99 88 77 66 55 44 33 22 11 0 0
Time out when waiting for ACK
```

Thank you for your assistance.

**Comment by michelbarnich** [comment]
Something I forgot to mention: Reading cards works perfectly fine, I only encountered this specific HAL call not working.

**Comment by michelbarnich** [comment]
A small update:

I tried the [command from the Adafruit PN532 library](https://github.com/adafruit/Adafruit-PN532/blob/f4e1a91afd0163d8601b243ddcbb2a580da6552a/Adafruit_PN532.cpp#L1638), and HAL still returns -2. I've also tried commands mentioned in other issues, without success. This is what the command looks like:
```
uint8_t command[] = {
      0x8C,             // INIT AS TARGET
      0x00,             // MODE -> BITFIELD
      0x08, 0x00,       // SENS_RES - MIFARE PARAMS
      0xdc, 0x44, 0x20, // NFCID1T
      0x60,             // SEL_RES
      0x01, 0xfe, // NFCID2T MUST START WITH 01fe - FELICA PARAMS - POL_RES
      0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xc0,
      0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, // PAD
      0xff, 0xff,                               // SYSTEM CODE
      0xaa, 0x99, 0x88, 0x77, 0x66, 0x55, 0x44,
      0x33, 0x22, 0x11, 0x01, 0x00, // NFCID3t MAX 47 BYTES ATR_RES
      0x0d, 0x52, 0x46, 0x49, 0x44, 0x49, 0x4f,
      0x74, 0x20, 0x50, 0x4e, 0x35, 0x33, 0x32 // HISTORICAL BYTES
  };
```

**Comment by Pr77Pr77** [comment]
Did you get it to work? I have the same problem.
