### ISSUE TITLE
Can I get some help with the tag emulation

### ISSUE THREAD

**Issue by jinzhangA** [Seeed-Studio/PN532#36]
I just tried the tag emulation example with Adafruit NFC breakout broad+Arduino Mega to emulation a tag with the example code. I tried to read it with Adafruit NFC breakout broad + libnfc. I used nfs-poll and read the uid and a few other things, but it didn't trigger the writing of ndef data at the Arduino end. What should I do with it?
I just start learn about NFC and found I have no clue about it. Is there any good place to start with?
I would be really appreciate if any one can help me out.

**Comment by xiongyihui** [comment]
Not sure if the libnfc supports reading nfc type 4 tag which the type is used by tag emulation example.
Have you tried to read the emulated tag with a nfc android phone? Or you can try [nfcpy library](https://nfcpy.readthedocs.org/en/latest/)
