### ISSUE TITLE
Is it bug or intentional ? --> status = MAClink.read() --> status is uint16_t whereas MAClink.read() is int16

### ISSUE THREAD

**Issue by mashhashkarma** [Seeed-Studio/PN532#41]
Hi,
 Truly very useful library.
Kindly help me. I see the follwing code in LLCP::read() function:
---------------------------------------------------
   **uint16**_t **status**;
    // Get INFO PDU
    do {
        **status = link.read**(buf, length);
        if (2 > status) {
            return -1;
 ---------------------------------------------------
However  **MACLink::read() returns int16_t.**
Is this a bug ?

**Comment by jlkalberer** [comment]
Yeah, that looks like a bug. link.read can definitely return -1 on failure.

**Comment by xiongyihui** [comment]
Thanks for reporting the bug. It should be `int16_t status`

**Comment by xiongyihui** [comment]
Fixed, thanks
