### ISSUE TITLE
Raw commands for mfocuino

### ISSUE THREAD

**Issue by Pascal66** [Seeed-Studio/PN532#48]
Where I can implement : 
//send raw command to pn532
  nfc.sendRawCommandCheckAck(buffer, len+5);
//read pn532 answer
  nfc.readRawCommandAnswer();

Using I2C librarie ?
@serztle use old adafruit librarie and @danielskowronski use SPI

**Comment by vivacarvajalito** [comment]
Hello friends, find the solution?

**Comment by Pascal66** [comment]
@vivacarvajalito no, i have rewrited a not fully working sketch, if you want to participate

**Comment by vivacarvajalito** [comment]
Thanks for you..You are awesome...You are me hero...

**Comment by Pillar1989** [comment]
I'll close the question and open it again if you need to discuss it later
