### ISSUE TITLE
Issue to run the Library with Arduino Uno board

### ISSUE THREAD

**Issue by sebastien0099** [Seeed-Studio/PN532#51]
Dear All,
I'm using an Arduino Uno with the Arduino 1.8.1 IDE from https://www.arduino.cc/ and I'm facing a problem to run the project.
I connected the NFC like mentioned in this datasheet https://dangerousthings.com/wp-content/uploads/PN532_Manual_V3-1.pdf
VCC 5V
GND GND
I2C Mode 
SDA A4/SDA 
SCL A5/SCL
I followed the steps and unzipped the project in the Arduino Library. At compilation I'm receiving a lot of warning. Then I can upload the project to the arduino board but it doesn't detect the board. 
Any idea what I do wrong? 
Thanks a lot

Warnings :

C:\Program Files (x86)\ArduinoCC\libraries\PN532\PN532.cpp: In member function 'uint8_t PN532::mifareclassic_WriteNDEFURI(uint8_t, uint8_t, const char*)':

C:\Program Files (x86)\ArduinoCC\libraries\PN532\PN532.cpp:567:56: warning: narrowing conversion of '(((int)len) + 5)' from 'int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]

     uint8_t sectorbuffer1[16] = {0x00, 0x00, 0x03, len + 5, 0xD1, 0x01, len + 1, 0x55, uriIdentifier, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

                                                        ^

C:\Program Files (x86)\ArduinoCC\libraries\PN532\PN532.cpp:567:77: warning: narrowing conversion of '(((int)len) + 1)' from 'int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]

     uint8_t sectorbuffer1[16] = {0x00, 0x00, 0x03, len + 5, 0xD1, 0x01, len + 1, 0x55, uriIdentifier, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

                                                                             ^

C:\Program Files (x86)\ArduinoCC\libraries\PN532\snep.cpp: In member function 'int16_t SNEP::read(uint8_t*, uint8_t, uint16_t)':

C:\Program Files (x86)\ArduinoCC\libraries\PN532\snep.cpp:99:31: warning: left shift count >= width of type

  uint32_t length = (buf[2] << 24) + (buf[3] << 16) + (buf[4] << 8) + buf[5];

                               ^

C:\Program Files (x86)\ArduinoCC\libraries\PN532\snep.cpp:99:48: warning: left shift count >= width of type

  uint32_t length = (buf[2] << 24) + (buf[3] << 16) + (buf[4] << 8) + buf[5];

                                                ^

**Comment by Pillar1989** [comment]
I'll close the question and open it again if you need to discuss it later.
