### ISSUE TITLE
Does tag emulation support Android 5.0+?

### ISSUE THREAD

**Issue by archerindigo** [Seeed-Studio/PN532#55]
Hi,

I have a PN532 module with Arduino Mega SPI interface and I tried the emulate_tag_ndef example. However, there is no response from Android devices. I tried with a Sony Xperia Z5 Dual (Android 6.0.1), a LG G2 (5.0.1) and a Samsung Galaxy Note 3 (5.0). None of them give a response. Does anyone tried that out?

Terry

**Comment by Pillar1989** [comment]
I didn't find any problems in my tests on Android 9, I'll close the question and open it again if you need to discuss it later.
