### ISSUE TITLE
Error while compiling PN532

### ISSUE THREAD

**Issue by zapper9595** [Seeed-Studio/PN532#57]
Hi, 
D:\Arduino Sketch\libraries\PN532\emulatetag.cpp:49:16: error: expected identifier before numeric constant

D:\Arduino Sketch\libraries\PN532\emulatetag.cpp:49:16: error: expected '}' before numeric constant

D:\Arduino Sketch\libraries\PN532\emulatetag.cpp:49:16: error: expected unqualified-id before numeric constant

D:\Arduino Sketch\libraries\PN532\emulatetag.cpp:49:31: error: expected declaration before '}' token

Currently I'm facing this problem. Totally clueless on how to fix. Advice needed! 
Arduino 1.8.3

**Comment by Pillar1989** [comment]
I'm sure the problem has been solved . I'll close the question and open it again if you need to discuss it later.
