### ISSUE TITLE
Avoid write error/edit a ndef record.

### ISSUE THREAD

**Issue by facetime88** [Seeed-Studio/PN532#59]
Hi,

I am new with nfc stuff. I have succesfully use this awesome library in my arduino project to read and write nfc tag consist of several ndef records.

As far as I know, the write function will erase the original message in the tag and write with the new one. I have problem several times when trying to write but resulting corrupted message when tap and remove too fast. I imagine a scenario if the nfc tag has a record valued with a payment balance and when writing is error this will make the ndef message corrupted, not just the related record, but other record also, because the original message seems will be replace on the fly with new message, regardless wether the writing will successfull or not. This will make the tag can't re-read again when writing result in error.

Is this how it works or I make a mistake? How do I avoid write error, or to make sure that even if the write is resulting an error, the original message won't be corrupted and can still re read for the next tap trial.

**Comment by Pillar1989** [comment]
I'll close the question and open it again if you need to discuss it later
