### ISSUE TITLE
Function readPassiveTargetID() works too slow

### ISSUE THREAD

**Issue by basil-ionin** [Seeed-Studio/PN532#60]
I'm using I2C for connection between my PN532 board and Arduino UNO. I'm using example iso14443a_uid.pde for reading Mifare uids in loop. If there is no card, function readPassiveTargetID(PN532_MIFARE_ISO14443A, &uid[0], &uidLength) must return false and otherwise - true. But in both cases this function works too slow, it has delay about 6 seconds.

So, because of this is blocking method I can't continue my program execution. Please, help me.

**Comment by jwktje** [comment]
I also have this issue. Any solution @basil-ionin ?

**Comment by Pillar1989** [comment]
I'll close the question and open it again if you need to discuss it later
