### ISSUE TITLE
SPI mode not working with nfc module v3 elechouse

### ISSUE THREAD

**Issue by facetime88** [Seeed-Studio/PN532#62]
I tried to use the example in SPI mode but it always said it didn't found the board. I tried before with I2C mode and works well. I need use the SPI mode for p2p transfer. It said Didn't find PN53x board.

Board: arduino due.

**Comment by garrett-davidson** [comment]
Any updates? I'm currently having the exact same issue.

**Comment by KillingJacky** [comment]
@facetime88 I don't think elechouse's staff will see the issue here.

**Comment by dimonDDL** [comment]
> 
> 
> Any updates? I'm currently having the exact same issue.

Have you tried using the S0 and S1 pins

**Comment by Pillar1989** [comment]
I'll close the question and open it again if you need to discuss it later
