### ISSUE TITLE
Grove NFC p2p

### ISSUE THREAD

**Issue by facetime88** [Seeed-Studio/PN532#63]
I just bought Grove nfc, its [wiki](http://wiki.seeedstudio.com/wiki/Grove_%EF%BC%8D_NFC) stated it is support for p2p and pointing library to this one.
Its wiki also stated Grove nfc supports UART and I2C. No mention for SPI.
While the p2p example here is showing only in SPI mode.

So how do use Grove nfc for p2p with this library?

**Comment by tvanfossen** [comment]
#include <NfcAdapter.h>
#include <PN532/PN532/PN532.h>
#include "SPI.h"
#include <PN532/PN532_HSU/PN532_HSU.h>
#include "PN532/PN532/snep.h"
#include "NdefMessage.h"

PN532_HSU pn532hsu(Serial);
SNEP nfc(pn532hsu);

uint8_t ndefBuf[128];



void setup(void) {
    SERIAL.begin(115200);
    SERIAL.println("NDEF Reader");
}

void loop(void) {
    SERIAL.println("Send a message to Peer");
    
    NdefMessage message = NdefMessage();
    message.addUriRecord("http://shop.oreilly.com/product/mobile/0636920021193.do");
    //message.addUriRecord("http://arduino.cc");
    //message.addUriRecord("https://github.com/don/NDEF");

    
    int messageSize = message.getEncodedSize();
    if (messageSize > sizeof(ndefBuf)) {
        SERIAL.println("ndefBuf is too small");
        while (1) {
        }
    }

    message.encode(ndefBuf);
    if (0 >= nfc.write(ndefBuf, messageSize)) {
        SERIAL.println("Failed");
    } else {
        SERIAL.println("Success");
    }

    delay(3000);
}

-----------------------------------------------------------------------------

Above does not work with hardware serial and a Grove NFC PN532 - is there a working version of code for UART and P2P?
