### ISSUE TITLE
Problem using with other inputs

### ISSUE THREAD

**Issue by jwktje** [Seeed-Studio/PN532#70]
I'm successfully using this library to read cards over SPI. But when I read cards in the loop continuously it slows down all other processes. To the point when reading push-buttons doesn't work anymore as the RFID reading takes so long that the button is not pressed anymore when the loop gets to checking it.

Is there a way to use this library nonblocking? Or prevent the delay it's causing?

**Comment by xiongyihui** [comment]
It's hard to support nonblocking API. You may have a try of that. Some functions have a timeout parameter which may help to adjust the delay.

**Comment by xiongyihui** [comment]
You may want to check the `readPassiveTargetID` function
