### ISSUE TITLE
SPI card emulation is not working 

### ISSUE THREAD

**Issue by dimonDDL** [Seeed-Studio/PN532#73]
After successfully connecting the PN532 to an arduino using SPI I successfully red the information from a few NFC cards. But when I tried to use the emulation example and trying to read it with MFRC522 nothing happens. Even if I tried to read only the UID there is also no response. I want to emulate a 7 byte UID of a card. But even the example without any change is not working.

**Comment by Pillar1989** [comment]
I'll close the question and open it again if you need to discuss it later

**Comment by jakubkrnac** [comment]
why did you close it when it's not solved yet??
