### ISSUE TITLE
I need to reinit PN532 after authentification error

### ISSUE THREAD

**Issue by Totoche95** [Seeed-Studio/PN532#74]
Hello,

Thanks for your work.
I use your librairy in SPI mode with Arduino uno and blue PN532 card from Banggood.
I works fine exept one thing : If i have authentification error on one sector , all sector after this sector cannot be authentified and accessed.
I round the problem by adding the line  : 
nfc.readPassiveTargetID(PN532_MIFARE_ISO14443A, uid, &uidLength);
in authentification error traitment.
So the sector after the sector not authentification can be accessed.  
Is it normal or is there a solution to that ?

Thanks
Yves,  France

-------------------------------------------------------------------------------------------------
if (success)
          {
            authenticated = true;
          }
          else
          {
            Serial.println("Authentication error");
            success1 = nfc.readPassiveTargetID(PN532_MIFARE_ISO14443A, uid, &uidLength); //Added to reinitialise card after authentification error
          }

**Comment by Pillar1989** [comment]
I'll close the question and open it again if you need to discuss it later
