### ISSUE TITLE
Activate is failed when using P2P_Push sample sketch with NFC Shiled V2.1

### ISSUE THREAD

**Issue by dandan0211** [Seeed-Studio/PN532#83]
I try to use P2P_Push sample with NFC Shield V2.1 but failed.

Regarding debug message, it seems fail to actiate PN532

Please let me know how to solve the problem?

I already find a little bug and made issue on #82. But I can not fix the problem.

The debug messaage on activate is as below.
------
Send a message to Peer
SAMConfig
write:  14 1 14 1
Time out when waiting for ACK
write:  8C 0 0 0 0 0 0 40 1 FE F BB BA A6 C9 89 0 0 0 0 0 0 0 0 FF FF 1 FE F BB BA A6 C9 89 0 0 A 46 66 6D 1 1 10 2 2 0 80 0
Time out when waiting for ACK
failed to activate PN532 as a target
Failed

**Comment by Pillar1989** [comment]
I'll close the question and open it again if you need to discuss it later
