### ISSUE TITLE
emulate_tag UID

### ISSUE THREAD

**Issue by jakubkrnac** [Seeed-Studio/PN532#87]
when i run [emulate_tag_ndef](https://github.com/Seeed-Studio/PN532/blob/arduino/PN532/examples/emulate_tag_ndef/emulate_tag_ndef.ino) sketch and read the PN532 with phone the UID is 00:00:00:00:00:00:00:00
and not 12:34:56 as it's written in the code. however i achieved changing UID by editing the NFCID2 (FeliCa Params) in uint8_t command[] in [emulatetag.cpp](https://github.com/Seeed-Studio/PN532/blob/arduino/PN532/emulatetag.cpp#L90). so i don't know if it's on purpose or not. 

also i want to know if it's possible to change the lenght of UID. so it's not 3 or 10 bytes long but for example 4 bytes long.

thanks

**Comment by Pillar1989** [comment]
@jakubkrnac What hardware do you use?  Maybe you can try our [library](https://github.com/Seeed-Studio/Seeed_Arduino_NFC) and our supporting products for testing.

**Comment by jakubkrnac** [comment]
i am using chinese PN532 module witch is probably FeliCa so that's why it uses the NFCID2 and not NFCID1. so let's forget about that. 

i want to know if it's possible to change the lenght of the UID. 

thanks

**Comment by Pillar1989** [comment]
Is this the hardware?
![image](https://user-images.githubusercontent.com/4081906/64541564-a6c2ab00-d354-11e9-96a7-27577d94a52e.png)

**Comment by jakubkrnac** [comment]
no it's not i said that is some chinese module. can you please answer if it's possible to change the lenght of UID??

**Comment by Pillar1989** [comment]
Different hardware in the software driver is still very different, I suggest you still where to buy, you go to him for help, this software is not a universal software.
