### ISSUE TITLE
Includes not working - PN532/PN532/PN532Interface.h: No such file or directory

### ISSUE THREAD

**Issue by cberetta** [Seeed-Studio/PN532#90]
I'm working on a project with your library and found out that the path inside includes was wrong _(at least for me)_. I deployed the library via GIT as told in the readme and then linked every single directory via "ln -s" in my library.

I use the "portable library" so inside my directory "/Documents/arduino/portable/sketchbook/libraries" I have all the 6 directory linked to the corresponding inside my GIT sources.
- PN532 -> ~/Documents/NFC/PN532
- PN532_HSU -> ~/Documents/NFC/PN532_HSU
and so on.

But when I try to run some of the examples I got error **"PN532/PN532/PN532Interface.h: No such file or directory"**

After some checking of my configuration I found that the only solution was to correct every includes in the sources. So I changed **"PN532/PN532/PN532Interface.h"** to **"PN532Interface.h"**. Basically I removed every occurrence of the full path for every includes inside the sources. With this changes I could compile everything and had no problem anymore with the path.

Am I missing something in the configuration?
Now if I pull a new update I have to redo all this work _(just a couple of "sed" but I do not like it)_.
Can you help?
Thanks.

**Comment by Pillar1989** [comment]
Please use this repo : https://github.com/seeed-Studio/Seeed_Arduino_NFC
