### ISSUE TITLE
Emulating and reading at same time 

### ISSUE THREAD

**Issue by giorgio80** [Seeed-Studio/PN532#92]
Hello , 

For my project I would need both to emulate and reading card .

It would be possible to do that as same time ?

My idea is to read card for half seco d and emulate card for same amount of time . To make the process transparent to user . 

Is this possible or I would need 2 modules?

**Comment by Pillar1989** [comment]
You definitely need two modules.

**Comment by cyberknight01** [comment]
> Hello ,
> 
> For my project I would need both to emulate and reading card .
> 
> It would be possible to do that as same time ?
> 
> My idea is to read card for half seco d and emulate card for same amount of time . To make the process transparent to user .
> 
> Is this possible or I would need 2 modules?

HI, do you finsh it ? i am doing the same thing, but i cannot emulate

**Comment by DavidDHansson** [comment]
I am in the same situation.

**Comment by Cincinnatu** [comment]
> Hello ,
> 
> For my project I would need both to emulate and reading card .
> 
> It would be possible to do that as same time ?
> 
> My idea is to read card for half seco d and emulate card for same amount of time . To make the process transparent to user .
> 
> Is this possible or I would need 2 modules?

This solution sounds feasible. Has the issue been resolved now?

**Comment by DavidTiimo** [comment]
> > Hello ,
> > For my project I would need both to emulate and reading card .
> > It would be possible to do that as same time ?
> > My idea is to read card for half seco d and emulate card for same amount of time . To make the process transparent to user .
> > Is this possible or I would need 2 modules?
> 
> This solution sounds feasible. Has the issue been resolved now?

I tried this, and it dosen't work optimally. It gives a bad user experience. I can share my code if you want to try it.

**Comment by Cincinnatu** [comment]
> > > 您好，对于我的项目，我需要模拟和读取卡。可以同时这样做吗？我的想法是读取卡片半秒并模拟相同时间的卡片。使进程对用户透明。这是否可能，或者我需要 2 个模块？
> > 
> > 
> > 这个解决方案听起来是可行的。问题现在解决了吗？
> 
> 我试过这个，但它并没有发挥最佳效果。它给人一种糟糕的用户体验。如果您想尝试，我可以分享我的代码。

Okay

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
