### ISSUE TITLE
Sector selection command

### ISSUE THREAD

**Issue by sebastian-1986** [Seeed-Studio/PN532#94]
Hello,

for my project I'm using the Seeed-Studio NFC shield with an Arduino Mega.
I want to use this setup to read and write the eeprom of a NT3H2211 chip.
With my current arduino project I'm able to read an write the pages on sector 0. 
In the next step I want to switch to from sector 0 to sector 1.
Is there any function in the Seeed-Studio PN532 library which i can use for the the sector selection command? 
Thanks

**Comment by Cincinnatu** [comment]
Has your problem been resolved?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
