### ISSUE TITLE
Linux paths incompatible with windows paths

### ISSUE THREAD

**Issue by Johannf78** [Seeed-Studio/PN532#95]
Libraries not found on all windows machines.
For example:
#include <PN532/PN532_SPI/PN532_SPI.h>

Forward slashes do not work in windows machines.
Please change to just one directory level deep and only.
#include <PN532_SPI.h>

**Comment by Johannf78** [comment]
Still having the same problem.
Code:
#include "PN532_SPI.h"

Error message:
ResolveLibrary(PN532/PN532/PN532Interface.h)
In file included from D:\OneDrive\Ardruino\NFC Reader\Seeed\Example Code\2020-05-14\2020-05-14.ino:1:0:
  -> candidates: []

C:\Program Files (x86)\Arduino\libraries\PN532_SPI/PN532_SPI.h:6:10: fatal error: PN532/PN532/PN532Interface.h: No such file or directory

 #include "PN532/PN532/PN532Interface.h"

          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

compilation terminated.

**Comment by Johannf78** [comment]
I managed to fix it.
One has to open each and every file in the library and remove the path PN532/PN532_SPI/
So just the file name included must remain.
Open all .cpp and all .h files in the library and edit them....

**Comment by net234** [comment]
Fixed :)
