### ISSUE TITLE
Message chaining for messages > 262 bytes

### ISSUE THREAD

**Issue by vmfox** [Seeed-Studio/PN532#96]
Summary of the issue: no (apparent) support of large data transfer (i.e. > 265 bytes)

Hi,

I'm using the PN532 to communicate with an android phone as:

Arduino Mega 2560 -> PN532 -> Android

After setting everything up and testing the basic data transfer I got to a point when I need to send data larger than 262 bytes supported by the inDataExchange().

Is there currently a function or a method/approach to send large messages i.e. as described in the chaining mechanism 7.4.5 DEP chaining mechanism - [PN532 User Manual](https://www.nxp.com/docs/en/user-guide/141520.pdf)?

I had a look through the library and couldn't find anything relevant and as I don't really have any spare time to append the library, would appreciate some guidance/code drafts along these lines.

Thanks.

**Comment by vmfox** [comment]
Potentially relevant [stackoverflow question](https://stackoverflow.com/questions/47820902/cannot-send-large-apdu-commands-with-libnfc-using-nfc-initiator-transceive-bytes)

**Comment by Cincinnatu** [comment]
Has your problem been resolved?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
