### ISSUE TITLE
PN532 Emulate NFC tag

### ISSUE THREAD

**Issue by AdonisBelo** [Seeed-Studio/PN532#98]
when I try to use pn532 to emulate an NFC tag, the arduino ide serial monitor doesn't show anything

**Comment by tvanfossen** [comment]
Emulation, at least in the library examples, is limited to SPI enabled PN532 boards, like the Elechouse flavor of PN532

**Comment by AdonisBelo** [comment]
I'm using an Elechouse pn532 connected via spi to an esp32, can you emulate it?

**Comment by RodrigoRP7** [comment]
Hi, was someone able to achieve this? I've been testing with multiple libraries and configurations, also using pn532 and esp32 and I am not obtaining any results

**Comment by Cincinnatu** [comment]
I will try soon. Has the issue been resolved for now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
